spring:
  application:
    name: acol-scada-manage  datasource:    url: jdbc:mysql://47.105.93.170/acolDataBase?characterEncoding=utf-8
    username: dave
    password: 756ZHANG
    #com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.jdbc.Driver
    druid:      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      filters: stat,wall,log4j
  session:    store-type: none
  jpa:    database: MYSQL
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      ddl-auto: update
server:  port: 8888eureka:
  instance:    instance-id: acol-scada-manage
    prefer-ip-address: true  client:    service-url:      defaultZone: http://47.105.93.170:7001/eureka
info:
  app.name: acol-scada-manage
  company.name: www.acolscada.cn
  app.api-help: swagger-ui.html
#security:
#  oauth2:
 ###      clientSecret: acolsecurity
 
security:
  basic:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
#browserConfig
acol:
  security:
    browser:
      loginPage: /login.html
      loginType: REDIRECT
      rememberMeSeconds: 86400
    code:
      imageCode:
        height: 23
        width: 67
        expireIn: 60