spring:
  application:
    name: acol-old-scada-api
    #session store type使用来存放session的存储方式    由于本应用暂无需将session放入redis的需求，故这里就可以将session store type设置为none.  session:    store-type: none
server:  port: 10088eureka:
  instance:    instance-id: acol-scada-api
    prefer-ip-address: true  client:    service-url:      defaultZone: http://47.105.93.170:7001/eureka
info:
  app.name: old-scada-api
  company.name: www.acolscada.cn
  app.api-help: swagger-ui.html
  
security:
  oauth2:
    client:
      clientId: acol-scada
      clientSecret: acol-Secret
      